# Generated by Django 5.0.6 on 2024-07-05 17:30

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=django_ckeditor_5.fields.CKEditor5Field(default='Hi There', null=True),
        ),
    ]
