# Generated by Django 5.0.6 on 2024-10-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipant',
            name='attended',
            field=models.BooleanField(default=False),
        ),
    ]
