# Generated by Django 5.0.6 on 2025-12-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('post', 'New Post'), ('comment', 'New Comment'), ('reply', 'Comment Reply'), ('like', 'Post Liked'), ('event_registration', 'Event Registration'), ('event_reminder', 'Event Reminder'), ('mention', 'Mentioned in Post')], max_length=30),
        ),
    ]
